print("To be")
print("or not")
print("to be")
print(" ")
print('"Life is what happens')
print('\t when')
print("\t you're busy making other plans"+'"')
print("\t John Lennon")
print(" ")
print('"The best way to predict the future   ')
print("\t is to")
print('\t \t invent it."')
print("\t \t \t Alan Kay")